controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: / # http://localhost:8000/
    controller: App\Controller\DefaultController::home

auth:
    path: /auth
    methods: ['POST']